### ISSUE TITLE
Duplicate menu items

### ISSUE THREAD

**Issue by markdorrill** [criticalmash/assemble-navigation#15]
This looks like a great piece of work.

I set up a test using your example assemblefile with my own content and I just have one simple problem in that the produced main menu contains duplicate items because of content in sub-folders.

Any ideas on how to prevent this or filter out the duplicates?

**Comment by criticalmash** [comment]
If your using the code from the README the duplication is created from the handlebars code that creates the menu. I added that so that the markup could be used in both desktop and mobile layouts.

On mobile, clicking a link in the top nav would reveal the submenu. From there you could select the index page or a child page. If I didn't include the index, mobile users would be able to use the page.

On desktop, I use a bit of css + media queries to hide the extra page.

``` css
// Top-bar customizations
@include breakpoint(medium up) {
  .menu.vertical > li.index-page{
    display: none;
  }
}
```

If mobile isn't an issue you can adjust the template. Just remove the first `li` under menu vertical. So it looks like this...

``` hbs
<ul class="menu vertical">
    <!-- remove first li element -->
     {{#each this.items}}
         <li class="{{#if isCurrentPage}}current-page{{/if}}"  data-linkid="{{linkId}}"><a href="{{{url}}}" >{{{title}}}</a></li>
     {{/each}}
</ul>
```

Please let me know how the site turns out. I'm planning to build a demo site to showcase how the module works and various ways to use it. So any feedback on problems encountered would be appreciated.
